apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: proofstack
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "change-me"
  POSTGRES_PASSWORD: "change-me"
  MINIO_SECRET_KEY: "change-me"
