apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: proofstack
spec:
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/kamomotov/proofstack-api@sha256:fa968bf18fe286a2ef00fb82732978331940749187560ea3469ce49852e8ea67
